markdown: rdiscount
highlighter: true
permalink: /:year/:month/:day/:title.html
name: "sadapple"
markdown: rdiscount

author: "chuan"
atom-baseurl: "http://sadapple.github.io"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://www.douban.com/people/31324984/
  - title: Blogroll
    class: fa fa-link
    href: /links.html

