# Site settings
title: Chuan Liu 
email: chuanliustat@gmail.com 
description: > # this means to ignore newlines until "baseurl:" Learn to Unlearn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: proudwolflc
github_username: sadapple

# Build settings
markdown: kramdown
